# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notman Occupants
email: info@notman.org
description: > # this means to ignore newlines until "baseurl:"
  Coming soon
baseurl: "./" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

# Build settings
exclude: ["README.md"]

page_gen:
  - data: 'organizations'
    template: 'organization-entry-html'
    name: 'ref'
    dir: 'organization'
    index_files: true
    extension: 'html'
  - index_files: true 
    data: 'organizations'
    template: 'organization-entry-json'
    name: 'ref'
    dir: 'organization' 
    extension: 'json'
  - data: 'people'
    template: 'person-html'
    name: 'ref'
    dir: 'person'
    index_files: true
    extension: 'html'
  - index_files: true 
    data: 'people'
    template: 'person-json'
    name: 'ref'
    dir: 'person' 
    extension: 'json'    